# JWT
jwt.secret=NMfbYqSj4c0WC5K3c8/0Vz7ELH891NKNGQfiiSApxu50y/9Zvo1xv4AGq8CRRjwZ
jwt.expirationMs=86400000

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Stripe
#stripe.secret.key=${STRIPE_SECRET_KEY}
#stripe.publishable.key=${STRIPE_PUBLISHABLE_KEY}

stripe.publishable.key=${STRIPE_PUBLISHABLE_KEY}